// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbUrl = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];
if (!dbUrl) {
  throw new Error(
    "Missing DATABASE_URL or DIRECT_URL in .env. Add your Supabase connection strings from Project Settings > Database."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
